### ISSUE TITLE
EFI <-> R2 Communication Request

### ISSUE THREAD

**Issue by apel1337** [xsh3llsh0ck/Deadwing#3]
Hello, could it be possible to provide a project what would directly communicate with Usermode without needing of any kernel component? Thank you, id like you to reach me out on discord: apel.lol

**Comment by xsh3llsh0ck** [comment]
> Hello, could it be possible to provide a project what would directly communicate with Usermode without needing of any kernel component? Thank you, id like you to reach me out on discord: apel.lol

@apel1337, hello! Sorry for the slow response.
Yes, it's possible. Predominantly all runtime services from `EFI_RUNTIME_SERVICES` generate an SMI (System Management Interrupt), this allows the OS runtime to move to another ring, which is the SMM. However, there is still a “problem” - all SMIs from runtime services essentially trigger root handlers, meaning that Child handlers (or any other, SW, Sx, etc) for example, will not be striggered. This means that you need to filter OS requests for SMM. It also means that you need to choose where you're going to locate the information for your own handler in SMM. This could actually be a buffer on the heap or a free page in your application, for example.

In theory, there's nothing stopping you from removing the GUID [here](https://github.com/xsh3llsh0ck/Deadwing/blob/465b2d14da5d258551ad6f40adb5303ff8c34878/Deadwing/Smi.c#L128), rewrite the [handler](https://github.com/xsh3llsh0ck/Deadwing/blob/465b2d14da5d258551ad6f40adb5303ff8c34878/Deadwing/Smi.c#L73) itself to receive information from outside the SMM context, excluding the DXE driver from loading (if you use QEMU OVMF: [1](https://github.com/xsh3llsh0ck/Deadwing/blob/465b2d14da5d258551ad6f40adb5303ff8c34878/Ovmf/OvmfPkgX64.dsc#L986), [2](https://github.com/xsh3llsh0ck/Deadwing/blob/465b2d14da5d258551ad6f40adb5303ff8c34878/Ovmf/OvmfPkgX64.fdf#L377)), removing the kernel mode driver, and modifying (or completely rewriting) my application for usermode.
